import React, { useEffect } from 'react';
import { updateDocumentSEO } from '../utils/seo';
import { FileText, Shield } from 'lucide-react';

export const TermsPage: React.FC = () => {
  useEffect(() => {
    updateDocumentSEO({
      title: 'Terms and Conditions - ZeeMark',
      description: 'Terms and Conditions governing the use of ZeeMark digital marketing guides, educational resources, and free browser tools.',
      canonicalPath: '/terms',
    });
  }, []);

  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-10 sm:py-16 space-y-10">
      
      <header className="space-y-3 border-b border-slate-200 dark:border-slate-800 pb-8">
        <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-slate-100 dark:bg-slate-800 text-slate-700 dark:text-slate-300 text-xs font-bold uppercase tracking-wider">
          <FileText size={14} className="text-indigo-500" />
          <span>User Agreement</span>
        </div>
        <h1 className="text-3xl sm:text-4xl font-extrabold text-slate-900 dark:text-white tracking-tight">
          Terms and Conditions
        </h1>
        <p className="text-xs sm:text-sm text-slate-500">
          Last updated: January 10, 2026
        </p>
      </header>

      <div className="space-y-8 text-sm sm:text-base text-slate-700 dark:text-slate-300 leading-relaxed">
        
        <section className="space-y-3">
          <h2 className="text-xl font-bold text-slate-900 dark:text-white">1. Agreement to Terms</h2>
          <p>
            By accessing and using ZeeMark (the "Website"), you agree to be bound by these Terms and Conditions and our Privacy Policy. If you do not agree with any of these terms, you are prohibited from using or accessing this site.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-xl font-bold text-slate-900 dark:text-white">2. Use License and Intellectual Property</h2>
          <p>
            Unless otherwise stated, ZeeMark and/or its licensors own the intellectual property rights for all material on ZeeMark. All intellectual property rights are reserved. You may access this from ZeeMark for your own personal and commercial educational use subjected to restrictions set in these terms:
          </p>
          <ul className="list-disc pl-5 space-y-1 text-xs sm:text-sm">
            <li>You must not republish substantial article text from ZeeMark without proper attribution.</li>
            <li>You must not sell, rent or sub-license material from ZeeMark.</li>
            <li>You must not duplicate, scrape, or systematically copy our free tools or proprietary software logic.</li>
          </ul>
        </section>

        <section className="space-y-3">
          <h2 className="text-xl font-bold text-slate-900 dark:text-white">3. Permissible Use of Free Marketing Tools</h2>
          <p>
            You are free to use the captions, headlines, hashtags, ad copy, and SEO titles generated by ZeeMark's browser tools for your personal, business, or client marketing campaigns without royalty fees or attribution. However, the automated scraping or continuous bot exploitation of our site is strictly forbidden.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-xl font-bold text-slate-900 dark:text-white">4. Disclaimer of Warranties</h2>
          <p>
            The materials and tools on ZeeMark are provided on an 'as is' basis. ZeeMark makes no warranties, expressed or implied, and hereby disclaims all other warranties including without limitation implied warranties or conditions of merchantability or fitness for a particular purpose.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-xl font-bold text-slate-900 dark:text-white">5. Limitations of Liability</h2>
          <p>
            In no event shall ZeeMark or its suppliers be liable for any damages (including, without limitation, damages for loss of data or profit, or due to business interruption) arising out of the use or inability to use the materials on ZeeMark.
          </p>
        </section>

        <section className="space-y-3 pt-4 border-t border-slate-200 dark:border-slate-800">
          <h2 className="text-xl font-bold text-slate-900 dark:text-white">6. Governing Law</h2>
          <p>
            These terms and conditions are governed by and construed in accordance with the laws of the United States, and you irrevocably submit to the exclusive jurisdiction of the courts in that state or location.
          </p>
        </section>

      </div>

    </div>
  );
};
